FROM golang:1.18-buster AS module-builder

RUN apt-get update && apt-get install -y git

WORKDIR /app
COPY go.mod ./
COPY go.sum ./

ARG MODULE_NAME

RUN go mod download

COPY . .

RUN go build -o ${MODULE_NAME}
